<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-07-20T00:50:14 IST" name="Suite" finished-at="2024-07-20T00:50:40 IST" duration-ms="25721">
    <groups>
    </groups>
    <test started-at="2024-07-20T00:50:14 IST" name="test" finished-at="2024-07-20T00:50:40 IST" duration-ms="25721">
      <class name="com.netbanking.testcases.TC002_LoginDDT_Test">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:com.netbanking.testcases.TC002_LoginDDT_Test@55fe41ea]" started-at="2024-07-20T00:50:14 IST" name="setup" finished-at="2024-07-20T00:50:16 IST" duration-ms="1667" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="ddt_Test(java.lang.String,java.lang.String)[pri:0, instance:com.netbanking.testcases.TC002_LoginDDT_Test@55fe41ea]" started-at="2024-07-20T00:50:17 IST" name="ddt_Test" data-provider="testdata" finished-at="2024-07-20T00:50:27 IST" duration-ms="9921" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr581547]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[EsezYqu]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ddt_Test -->
        <test-method signature="ddt_Test(java.lang.String,java.lang.String)[pri:0, instance:com.netbanking.testcases.TC002_LoginDDT_Test@55fe41ea]" started-at="2024-07-20T00:50:27 IST" name="ddt_Test" data-provider="testdata" finished-at="2024-07-20T00:50:30 IST" duration-ms="3474" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[mng64321]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Dsxza]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.netbanking.testcases.TC002_LoginDDT_Test.ddt_Test(TC002_LoginDDT_Test.java:26)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ddt_Test -->
        <test-method signature="ddt_Test(java.lang.String,java.lang.String)[pri:0, instance:com.netbanking.testcases.TC002_LoginDDT_Test@55fe41ea]" started-at="2024-07-20T00:50:30 IST" name="ddt_Test" data-provider="testdata" finished-at="2024-07-20T00:50:34 IST" duration-ms="3978" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[mhg4532]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[dxsvb]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.netbanking.testcases.TC002_LoginDDT_Test.ddt_Test(TC002_LoginDDT_Test.java:26)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ddt_Test -->
        <test-method signature="ddt_Test(java.lang.String,java.lang.String)[pri:0, instance:com.netbanking.testcases.TC002_LoginDDT_Test@55fe41ea]" started-at="2024-07-20T00:50:34 IST" name="ddt_Test" data-provider="testdata" finished-at="2024-07-20T00:50:40 IST" duration-ms="5511" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr581547]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[EsezYqu]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ddt_Test -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.netbanking.testcases.TC002_LoginDDT_Test@55fe41ea]" started-at="2024-07-20T00:50:40 IST" name="tearDown" finished-at="2024-07-20T00:50:40 IST" duration-ms="279" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.netbanking.testcases.TC002_LoginDDT_Test -->
    </test> <!-- test -->
  </suite> <!-- Suite -->
</testng-results>
